modLoader = "javafml"
loaderVersion = "${neo_loader_version}"
issueTrackerURL = "${issues}" #optional
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
updateJSONURL = "${update}" #optional
displayURL = "${homepage}" #optional
logoFile = "assets/acmexamplemod/icon.png" #optional
authors = "${authors}" #optional
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "${architectury_version}"
ordering = "AFTER"
side = "BOTH"
